apiVersion: v1
kind: Service
metadata:
  name: {{ Values.service.name }}
  annotations:
    service.beta.kubernetes.io/service-name: {{ include "redis-cluster-ha.fullname" . }}
  labels:
    {{- include "redis-cluster-ha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    {{- include "redis-cluster-ha.selectorLabels" . | nindent 4 }}
