---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-cluster-ha.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis-cluster-ha.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.redisClusterName }}
  replicas: 1
  selector:
    matchLabels:
      app: redis-sts
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-sts
    spec:
      volumes:
        - name: redis-data-vol
          persistentVolumeClaim:
            claimName: redis-{{ .Values.namespace }}-pvc
        - name: redis-bootstrap-cm-vol
          configMap:
            name: redis-bootstrap-cm-dev
        - name: wf-env-vol-dev
          secret:
            secretName: wf-api-secret-dev
            items:
            - key: env_file
              path: .env

      initContainers:
      - name: redis-init
        image: busybox
        command: ["sh", "-c", "ls -la /redis-dump/"]
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: redis-data-vol
          mountPath: /redis-dump

      - name: redis-dump
        image: minio/mc 
        env:
        - name: BACKUP_FREQUENCY
          value: "before-redis-cluster-updated"
        command: ["sh", "-c", "cp /tmp/configmap/backup-database.sh /usr/local/bin/backup-database.sh && chmod +x /usr/local/bin/backup-database.sh && bash /usr/local/bin/backup-database.sh"]
        volumeMounts:
        - name: redis-data-vol
          mountPath: /redis-dump
        - name: redis-bootstrap-cm-vol
          mountPath: /tmp/configmap
        - name: wf-env-vol-dev
          mountPath: /tmp/secrets

      containers:
      - name: redis-server
        image: bwalia/redis:latest
        volumeMounts:
        - name: redis-data-vol
          mountPath: /data
      # Moved to cronjob    
      # - name: redis-dump-sidecar
      #   image: minio/mc 
      #   env:
      #   - name: BACKUP_FREQUENCY
      #     value: "hourly"
      #   command: ["sh", "-c", "cp /tmp/configmap/backup-database.sh /usr/local/bin/backup-database.sh && chmod +x /usr/local/bin/backup-database.sh && bash /usr/local/bin/backup-database.sh hourly"]
      #   volumeMounts:
      #   - name: redis-data-vol
      #     mountPath: /redis-dump
      #   - name: redis-bootstrap-cm-vol
      #     mountPath: /tmp/configmap
      #   - name: wf-env-vol-dev
      #     mountPath: /tmp/secrets

